version: '3.9'
services:
  server:
    container_name: 'server'
    build: .
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - db
    networks:
      - net_A
  db:
    container_name: 'db'
    image: mongo:${MONGO_VERSION}
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ../zad01/mongodb:/data/db
    networks:
      - net_A
    
networks:
  net_A:
    external: false
    name: net_A
    driver: bridge