version: "3"
services:
  redis:
    container_name: redis
    image: redislabs/redismod
    ports:
      - "6379:6379"
    networks:
      - my_network

  db:
    container_name: postgres
    build: ./db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=user
      - POSTGRES_USER=postgres
    networks:
      - my_network

  web:
    container_name: web
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user
    networks:
      - my_network

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
      - APP_HOST=web
      - APP_PORT=3000
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    networks:
      - my_network

networks:
  my_network:
    external: false
    name: my_network